projectHome/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using mor1.Data.IRepositories;
using mor1.Models;
using mor1.Models.IdentityEntities;

namespace mor1.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHomepageRepo _homepageRepo;

        public HomeController(IHomepageRepo homepageRepo)
        {
            _homepageRepo = homepageRepo;
        }

        public async Task<IActionResult> Index()
        {
            //create new list and add the filename to it for homepage display
            List<string> resultList = new List<string>();

            var result1 = await _homepageRepo.GetAllSlides();
            foreach(var item in result1)
            {
                resultList.Add(item.Filename);
            }

            return View(nameof(Index), resultList);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult LoginView()
        {
            return PartialView("_LoginModalPartial");
        }
    }
}

projectHome/Controllers/ReqQuotationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using mor1.Data.IRepositories;
using mor1.Models;
using mor1.Models.IdentityEntities;
using mor1.ViewModels;

namespace mor1.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class ReqQuotationController : Controller
    {
        private readonly ICompServiceRepo _reqQuoteRepo;
        private readonly ICountryRepo _countryRepo;
        private readonly IPropertyRepo _propertyRepo;

        public ReqQuotationController(ICompServiceRepo reqQuoteRepo, ICountryRepo countryRepo, IPropertyRepo propertyRepo)
        {
            _reqQuoteRepo = reqQuoteRepo;
            _countryRepo = countryRepo;
            _propertyRepo = propertyRepo;
        }

        //to direct to services selection page
        public IActionResult Index()
        {
            reqQuoteIndexVM vm = new reqQuoteIndexVM()
            {
                ServiceCategories = _reqQuoteRepo.GetAllCat().ToList(),
                Services = _reqQuoteRepo.GetAllServices().OrderBy(a => a.CatID).ToList()
            };


            return View(vm);
        }

        [HttpPost]
        public IActionResult Index(reqQuoteIndexVM vm)
        {
            var chkBoxArr = HttpContext.Request.Form["subCatSelect"];
            return RedirectToAction(nameof(reqQuoteForm), routeValues: new { chkBoxArr2 = chkBoxArr });
        }

        //to direct to form page
        public IActionResult reqQuoteForm(string[] chkBoxArr2)
        {
            reqQuoteFormVM vm = new reqQuoteFormVM()
            {
                SelectCountry = _countryRepo.GetAll()
                                .Select(s => new SelectListItem { Value = s.ID.ToString(), Text = s.CountryName })
                                .OrderBy(b => b.Text)
                                .ToList(),
                PropertyTypes = _propertyRepo.GetAllPropertyTypes().ToList(),
                SelectPropertyStatus = _propertyRepo.GetAllPropertyStatus()
                                 .Select(s => new SelectListItem { Value = s.ID.ToString(), Text = s.Status })
                                 .ToList(),
                SelectedServices = _reqQuoteRepo.GetServicesListById(chkBoxArr2).ToList()
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult reqQuoteForm(reqQuoteFormVM vm)
        {
            //=========== add qoute form ==============
            var addedId = _reqQuoteRepo.AddQuoteForm(vm.reqQuoteForm);

            //=========== add selected services ===========
            foreach(var service in vm.SelectedServices)
            {
                _reqQuoteRepo.AddSelectedService(addedId, service.ID);
            }

            //======== upload file ==============
            if (vm.FloorPlanFile != null && vm.FloorPlanFile.Count() > 0)
            {
                var files = vm.FloorPlanFile;
                //long size = files.Sum(f => f.Length);
                // full path to file in temp location
                //var filePath = Path.GetTempFileName();
                var filePath = commonName.floorPlanFilePath;
                var modifiedFileName = "";
                foreach (var formFile in files)
                {
                    if (formFile.Length > 0 && FileExtensions.IsImage(formFile.FileName))
                    {
                        modifiedFileName = addedId + "_" + formFile.FileName;
                        if (_reqQuoteRepo.AddFloorPlanFile(modifiedFileName, null, addedId) > 0)
                        {
                            using (var stream = new FileStream(Path.Combine(filePath, modifiedFileName), FileMode.Create))
                            {
                                formFile.CopyTo(stream);
                            }
                        }
                    }
                    else
                    {
                        break;
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = RoleNames.superAdmin)]
        public async Task<IActionResult> ViewAllFormsData()
        {
            var results = await _reqQuoteRepo.GetReqQuoteForms();
            return View(results);
        }

    }
}

projectHome/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

projectHome/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

projectHome/Views/Home/Index.cshtml
@model List<string>
@using mor1.Models
@{
    ViewData["Title"] = "Home Page";
    var homeslidesUrl = commonName.homeSlideFilePathUrl;
    var modelCount = Model.Count();
    //loop through model and add homeslidesUrl to each model name
    for (byte i =0; i<modelCount; i++)
    {
        Model[i] = homeslidesUrl + Model[i];
    }

    //copy video path to var
    var videomp4 = "/videos/" + "Eric.mp4";
    var videoogg = "/videos/" + "Eric.ogg";
}

<link rel="stylesheet" href="~/css/homepage.css">



<!--============== Swiper slider ================ -->
<!-- Slider main container -->
<div class="swiper-container main-slider" id="myCarousel">
    <div class="swiper-wrapper">

        <!--load video if weekend-->
        @if (DateTime.Now.DayOfWeek == DayOfWeek.Saturday || DateTime.Now.DayOfWeek == DayOfWeek.Sunday)
        {
            <div class="swiper-slide slider-bg-position" style="background-color: black;" data-hash="slide1">
                <!-- add muted if Chrome/Safari can't play -->
                <video class="slider-video" preload="auto" loop autoplay muted controls
                       style="visibility: visible; width: 100%; height: 100%;">
                    <source src= "@videomp4" type="video/mp4">
                    <source src="@videoogg" type="video/ogg">
                </video>
            </div>

        }
        else
        {
            <div class="swiper-slide slider-bg-position" style="background: url('@Model[0]');"
                 data-hash="slide1">
                <div class="slideBox mySlide1">
                    <div class="card">
                        <div id="slideTitle">Build Your Dream Home With Us</div>
                        <p><a href="#" class="btn myBtnOrange btn-lg">DISCOVER NOW!</a></p>
                    </div>
                </div>

            </div>

            <div class="swiper-slide slider-bg-position" style="background: url('@Model[1]'); background-position: center center !important;"
                 data-hash="slide2">
                <div class="slideBox mySlide2" style="background-color: transparent;">
                    <div class="card">
                        <div id="slideTitle2">Singapore's No.1 Online Portal For Renovation Services</div>
                        <p><a href="#" class="btn myBtnOrange btn-lg">LEARN MORE</a></p>
                    </div>
                </div>
            </div>

            <div class="swiper-slide slider-bg-position" style="background-image: url('@Model[2]');"
                 data-hash="slide3">
                <div class="slideBox mySlide3" style="background-color: rgba(0, 0, 0, 0.3);">
                    <div class="card">
                        <div id="slideTitle3">The Right Choice For You and Your Family</div>
                    </div>
                </div>
            </div>
        }



    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
    <!-- Add Navigation -->
    <div class="swiper-button-prev"><i class="fa fa-chevron-left"></i></div>
    <div class="swiper-button-next"><i class="fa fa-chevron-right"></i></div>
</div>



<!--======== about section ==============-->
<div class="" id="aboutSec">
    <div class="container">
        <div id="aboutSecTitle">
            <div>Looking to renovate, but don't know where to go to?</div>
            <div>You are in the right place.</div>
            <div>With 3 simple steps, we show you the door to the best contractors in town.</div>
        </div>
        <div class="card-deck" id="servStepsWrapper">
            <div class="col-4 card">
                <div class="">
                    <div class="stepIcon">
                        &#10102;
                    </div>
                </div>
                <div class="stepDesc">
                    <div>Select the type of services</div>
                </div>
            </div>
            <div class="col-4 card">
                <div class="">
                    <div class="stepIcon">
                        &#10103;
                    </div>
                </div>
                <div class="stepDesc">
                    <div>Fill in your home particulars</div>
                </div>
            </div>
            <div class="col-4 card">
                <div class="">
                    <div class="stepIcon">
                        &#10104;
                    </div>
                </div>
                <div class="stepDesc">
                    <div>Submit</div>
                </div>
            </div>
        </div>
        <div style="text-align: center;">
            <a asp-controller="ReqQuotation" asp-action="Index" class="btn btn-lg myBtnOrange trans_300">GET YOUR FREE QUOTES NOW!</a>
        </div>
    </div>
</div>

<!--============= cards  ======================================= -->
<div class="" id="servSec">
    <div class="row">
        <div class="servSecImgWrapper col-md-6">
            <div class="servSecImg" style="background-image: url('/images/architect.jpeg');"></div>
        </div>
        <div class="col-md-6" id="servSecDescWrapper">
            <div id="servSecTitle">
                <div>SERVICES FOR YOU</div>
            </div>
            <div class="row servCatSec">
                <div class="col-6">
                    <div class="servIcon">
                        <i class="fas fa-pencil-alt"></i>
                    </div>
                    <div>Professional Services</div>
                </div>
                <div class="col-6">
                    <div class="servIcon">
                        <i class="fas fa-home"></i>
                    </div>
                    <div>Renovation Contractor</div>
                </div>
            </div>
            <div class="row servCatSec">
                <div class="col-6">
                    <div class="servIcon">
                        <i class="fas fa-archive"></i>
                    </div>
                    <div>Supplier</div>
                </div>
                <div class="col-6">
                    <div class="servIcon">
                        <i class="fas fa-home"></i>
                    </div>
                    <div>Renovation Contractor</div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script src="~/js/homepage.js"></script>
}