projectHome/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using mor1.Data.IRepositories;
using mor1.Models;
using mor1.Models.CompanyModels;
using mor1.ViewModels;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace mor1.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class CompanyController : Controller
    {
        private readonly ICompanyRepo _companyRepo;
        private readonly ICompServiceRepo _compServiceRepo;

        public CompanyController(ICompanyRepo companyRepo, ICompServiceRepo compServiceRepo)
        {
            _companyRepo = companyRepo;
            _compServiceRepo = compServiceRepo;
        }

        public IActionResult Index()
        {
            return View();
        }

        #region Search

        public IActionResult SearchCompanies()
        {
            SearchCompVM vm = new SearchCompVM
            {
                ServiceCategories = _compServiceRepo.GetAllCat().ToList(),
                Services = _compServiceRepo.GetAllServices().Select(s=> new SelectListItem { Value = s.ID.ToString(), Text = s.Title }).ToList()
            };
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> SearchCompanies([FromBody]JObject reqData)
        {
            try
            {
                //get ajax reqData properties
                var servCat = JsonConvert.DeserializeObject<int[]>(reqData["servCatIn"].ToString());
                var serv = JsonConvert.DeserializeObject<int[]>(reqData["servIn"].ToString());
                int page = reqData["subseqPageIdxIn"].Value<int>();
                string sortOption = reqData["sortOptionIn"].Value<string>();

                //get results from DB based search input
                var results2 = await _companyRepo.GetSearchResults(reqData["searchIn"].ToString(), servCat, serv);
                
                //re-order results based on sort option
                if(sortOption == "rating")
                {
                    results2 = results2.OrderByDescending(b => b.OverallRating);
                }else if(sortOption == "nameAZ")
                {
                    results2 = results2.OrderBy(b => b.CompanyName);
                }else if(sortOption == "nameZA")
                {
                    results2 = results2.OrderByDescending(b => b.CompanyName);
                }

                //create paginated list. 3rd argument is page size
                var results = await PaginatedList<Company>.CreateAsync(results2, page==0 ? 1: page, 5);

                //if results is not null, return partial view with the results.
                if (results != null)
                {
                    return PartialView("_SearchResultsPartial", results);
                }
            }
            catch (Exception)
            {
                throw;
            }
            return null;
        }

        //function to return autocomplete results
        [HttpGet]
        public async Task<JsonResult> GetSearchAutocompResults(string reqData)
        {
            try
            {
                //get results from DB
                var result = await _companyRepo.GetSearchAutocompByInput(reqData);
                if( result != null)
                {
                    return Json(result);
                }
            }
            catch (Exception)
            {
                throw;
            }
            return null;
        }

        #endregion

        #region IndividualCompany

        //function to get individual company details
        public async Task<IActionResult> GetIndividualCompany(int id)
        {
            //get company details with comments from DB
            var results = await _companyRepo.GetCompanyWcommentsById(id);
            var vm = new IndvCompCommVM()
            {
                Company = results,
                CompComment = new CompComment()
            };
            return View("IndividualCompany", vm);
        }

        [HttpPost]
        public async Task<IActionResult> PostComment(IndvCompCommVM vm)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            //rating calculation
            vm.CompComment.Rating = (decimal)(vm.pmRating + vm.priceRating + vm.workManRating) / 3;

            //add comment to DB
            var returnId = await _companyRepo.AddComment(vm.CompComment);

            //update company rating in DB
            await _companyRepo.UpdateCompanyRating(vm.CompComment.CompID);

            //redirect to another action
            return RedirectToAction("GetIndividualCompany", new { id = vm.CompComment.CompID });
        }


        #endregion
    }
}

projectHome/Controllers/DirectoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using mor1.Data.IRepositories;

namespace mor1.Controllers
{
    public class DirectoryController : Controller
    {
        private readonly ICompanyRepo _companyRepo;

        public DirectoryController(ICompanyRepo companyRepo)
        {
            _companyRepo = companyRepo;
        }

        public IActionResult Index()
        {
            return View(_companyRepo.DirectoryGetAll());
        }

        [HttpGet]
        public async Task<JsonResult> GetDirListByInitial(string reqData)
        {
            try
            {
                var results = await _companyRepo.DirGetByInitial(reqData);
                if(results != null)
                {
                    return Json(results);
                }
            }
            catch (Exception)
            {
                throw;
            }
            return null;
        }
    }
}

projectHome/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mor1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">*@
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        <link rel="stylesheet" href="~/lib/swiper-4.4.1/css/swiper.min.css">
        @*<link rel="stylesheet" href="~/css/site.css" />*@
        <link rel="stylesheet" href="~/css/common.css" />
        <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.min.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <partial name="_Navbar" />

    <partial name="_CookieConsentPartial" />

    <div class="topNavBuffer" style="margin-bottom: 12vh;">

    </div>
        
    <!--=== below is to disable container for homepage to facilitate slider full width. And also for having top margin ===-->
    @{
        var cont = "myBodyContent";
    }
    @if (ViewData["Title"].ToString().Equals("Home Page"))
    {
        cont = "myHomeBodyContent";
    }
    <!--===================================================================================-->

            <div class="@cont body-content">
                @RenderBody()
                @*<hr />*@
                <footer>
                    <p>
                        &copy;
                        <script type="text/javascript">document.write(new Date().getFullYear());</script> - Project Home
                    </p>
                </footer>
            </div>

            <environment include="Development">
                <script src="~/lib/jquery/dist/jquery.js"></script>
                <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
                <!-- Popper JS -->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
                <script src="~/lib/swiper-4.4.1/js/swiper.min.js"></script>
                @*<script src="~/js/site.js" asp-append-version="true"></script>*@
                <script src="~/js/common.js" asp-append-version="true"></script>
                <script src="~/lib/slick-1.8.1/slick.min.js"></script>
                @*<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>*@
            </environment>
            <environment exclude="Development">
                <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                        asp-fallback-test="window.jQuery"
                        crossorigin="anonymous"
                        integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
                </script>
                <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/4.0.0/bootstrap.min.js"
                        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                        crossorigin="anonymous"
                        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
                </script>
                <script src="~/js/site.min.js" asp-append-version="true"></script>
            </environment>

            @RenderSection("Scripts", required: false)
    </body>
</html>

projectHome/Views/Shared/_LoginModalPartial.cshtml
<div class="modal-body loginModalBody">
    <form action="" style="padding: 10px;">
        <div class="form-group formDiv">
            <input type="text" class="form-control formInput">
            <label for="" class="modalLabel">Email Address</label>
        </div>
        <div class="form-group formDiv">
            <input type="password" class="form-control formInput">
            <label for="" class="modalLabel">Password</label>
        </div>
        <div style="margin-top: 30px;">
            <input type="submit" value="log   in" class="btn transparentBtn" style="width: 30%;">
            <span>&nbsp;&nbsp;OR&nbsp;&nbsp;</span>
            <a href="" class="btn transparentBtn transparentBtn-green" style="width: 60%;">
                Register
                New Account
            </a>
        </div>
    </form>
</div>

projectHome/Views/Shared/_Navbar.cshtml
<!--=========== top navbar =================-->
<div class="fixed-top navTop">
    <!-- navbar1 . use py-0 to remove padding to adjust navbar height-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-0" id="navbar1">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="~/images/myCompanyLogo.png" alt="nologo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a asp-controller="Company" asp-action="SearchCompanies">Search</a>

        <div class="collapse navbar-collapse navbarSupportedContent" id="">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item socialIcons">
                    <a href="#" data-toggle="tooltip" data-placement="auto" title="Pinterest">
                        <i class="fab fa-pinterest"
                           aria-hidden="true" style="color: #bd081b;"></i>
                    </a>
                    <a href="#" data-toggle="tooltip" data-placement="auto" title="Instagram">
                        <i class="fab fa-instagram"
                           aria-hidden="true" style="color: #8f4ac7;"></i>
                    </a>
                    <a href="#" data-toggle="tooltip" data-placement="auto" title="Facebook">
                        <i class="fab fa-facebook"
                           aria-hidden="true"  style="color: blue;"></i>
                    </a>
                    <a href="#" data-toggle="tooltip" data-placement="auto" title="Twitter">
                        <i class="fab fa-twitter"
                           aria-hidden="true"></i>
                    </a>
                </li>

                <partial name="_LoginPartial" />
            </ul>
        </div>
    </nav>

    <!-- navbar2 . use py-0 to remove padding to adjust navbar height-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-0" id="navbar2">
        <div class="collapse navbar-collapse navbarSupportedContent" id="">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">
                        Home
                        <!-- <span class="sr-only">(current)</span> -->
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="ReqQuotation" asp-action="Index">Get Free Quotes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Tenant Project</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Market Place & Bidding</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Directory" asp-action="Index">Directory</a>
                </li>
            </ul>
        </div>
    </nav>
</div>























@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@*<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">mor1</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>*@

projectHome/Views/Shared/_SearchResultsPartial.cshtml
@model mor1.Models.PaginatedList<mor1.Models.CompanyModels.Company>

@if (Model != null)
{
    <input type="hidden" data-totalPages="@Model.TotalPages" id="totalPages" />
    <div id="paginationSec">
        <ul class="pagination d-flex" style="margin-bottom: 0px;">
            <li class="page-item"><a class="page-link" href="#" data-subseqPageId="@(Model.PageIndex-1)">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#" data-subseqPageId="@(Model.PageIndex+1)">Next</a></li>
        </ul>
    </div>


    <div>
        <table style="width: 100%;">
            <thead>
                <tr>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var comp in Model)
                {
                <tr>
                    <td>
                        <div>
                            <a asp-controller="Company" asp-action="GetIndividualCompany" asp-route-id="@comp.ID" class="compHref">
                                <div class="card trans_300">
                                    <div class="container-fluid">
                                        <div class="row">
                                            <div class="col-md-2" style="background-color: greenyellow;">
                                                <div class="compLogo" style="background-image: url('/images/@comp.CompanyLogoFilename')"></div>
                                            </div>
                                            <div class="col-md-5">
                                                <div class="compName">@comp.CompanyName</div>
                                                <div><i class="fas fa-map-marker-alt"></i>&nbsp; @comp.Address</div>
                                                <div><i class="fas fa-envelope-square"></i>&nbsp; @comp.Email</div>
                                                <div><i class="fas fa-phone"></i>&nbsp; @comp.PhoneNum</div>
                                                <div>@comp.CompanyRegNum</div>
                                                <div>
                                                    Click to read more.....
                                                </div>
                                            </div>
                                            <div class="col-md-3">
                                                <div><strong></strong></div><div>
                                                    <ul class="servList">
                                                        @foreach (var serv in comp.CompServList)
                                                        {
                                                            <li>@serv.Title</li>
                                                        }
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="col-md-2" style="height: inherit;">
                                                <div class="" style="top: 50%; position: relative; transform: translateY(-50%); text-align: center;">
                                                    <div>
                                                        <strong>Rating</strong>
                                                    </div>
                                                    <div class="compRating" style="margin: 0 auto;">
                                                        @comp.OverallRating
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </td>
                </tr>

                }
                    
            </tbody>
        </table>
    </div>

}


@section scripts{
    <script type="text/javascript">
    </script>
}